POST http://localhost:5149/graph
content-type: application/json

    {
    "labels": {
        "title": "Math Progress",
        "x-axis": "Date",
        "y-axis": "DCPM"
    },
    "x-axis-data": [
        "10/1",
        "10/8",
        "10/15"
    ],
    "y-axis-data": [
        "13",
        "16",
        "15"
    ]
    }

###
POST http://localhost:5149/scheduler
content-type: application/json

        {"students":[
            {
              "id": 1,
              "name": "Ryan",
              "teacher": "Jennings",
              "blocks": []
            },
            {
              "id": 2,
              "name": "Brian",
              "teacher": "James",
              "blocks": []
            },
            {
              "id": 3,
              "name": "Jeff",
              "teacher": "Riley",
              "blocks": []
            },
            {
              "id": 4,
              "name": "Marley",
              "teacher": "Harris",
              "blocks": []
            },
            {
              "id": 5,
              "name": "Jeff ",
              "teacher": "Jenkins",
              "blocks": []
            },
            {
              "id": 5,
              "name": "Tom ",
              "teacher": "Jenkins",
              "blocks": []
            },
            {
              "id": 5,
              "name": "Petey ",
              "teacher": "Jenkins",
              "blocks": []
            }
          ],
            "teachertimes": {
                "Jenkins": ["10:30", "11:00"],
                "Harris": ["10:30", "12:30"],
                "Jennings": ["1:00"],
                "Riley": ["2:15"],
                "James": ["9:00", "9:30", "11:30"]
            }
        }
###
POST http://localhost:5149/lessonplan
content-type: application/json

    "Write a lesson plan for a small group of 2nd graders learning to tell time to the nearest five minutes."
###
POST http://localhost:5149/outcomes
content-type: application/json

    {
        "2024": {
            "Intervention Started": 4,
            "Dismissed to Tier 1": 1,
            "Return to Intervention": 2
        }
    }

###
GET http://localhost:5149/outcomes
content-type: application/json

###

POST http://localhost:5149/schedulestudents/4
content-type: application/json


   {
    "Id": 1,
    "Name": "BeeBop Foo",
    "Teacher": "Adams"
    }

###

POST http://localhost:5149/scheduleastudent/4
content-type: application/json


   {
    "Id": 3,
    "Time": "11:30 AM",
    "Grade": "3rd Grade"
    }

###

POST http://localhost:5149/addblock
content-type: application/json

{
    "Time": "10:00",
    "Grade": "4th"
}

###
POST http://localhost:5149/addblock
content-type: application/json

{
    "Time": "11:00",
    "Grade": "3rd"
}

###
GET http://localhost:5149/blocks
content-type: application/json

###
GET http://localhost:5149/currentuser
content-type: application/json

###
GET http://localhost:5149/students
content-type: application/json

###

GET http://localhost:5149/student/2
content-type: application/json

###

POST http://localhost:5149/addstudent
content-type: application/json

{
    "Name": "BeeBop Foo",
    "Teacher": "Adams"
}

###
POST http://localhost:5149/addstudent
content-type: application/json

{
    "Name": "Cranky Jay",
    "Teacher": "Adams"
}

###
//update a student
PUT http://localhost:5149/student/3
content-type: application/json

{
    "Name": "Borgo Fonkers",
    "Teacher": "Lorngings"
}

###
//delete a student
DELETE http://localhost:5149/student/2
content-type: application/json

{}

###
//register a user
POST http://localhost:5149/register/
content-type: application/json

{
    "email": "dc.1989@gmail.com",
    "password": "Bl@hbl4h"
}

###
//login to user account

POST http://localhost:5149/login/
Content-Type: application/json

{
    "email": "dc.1989@gmail.com",
    "password": "Bl@hbl4h"
}